Добавлен Web netty
KwakYV/wpz pull request #13
Opened 2022-07-20 07:26 UTC by EvgenyKhavdey

2022-07-20 15:05 UTC, KwakYV requested changes

2022-07-20 15:05 UTC, KwakYV commented on src/main/java/ru/wpz/nio_server/WebSocketChannelInitializer.java
> +        pipeline.addLast("httpObjectAggregator", new HttpObjectAggregator(8192));
А что это  за magic numbers - 8192

2022-07-20 15:05 UTC, KwakYV commented on src/main/java/ru/wpz/nio_server/WebSocketHandler.java
> +        ctx.writeAndFlush(messageDto)ж
ж - будет валиться с ошиькой

2022-07-20 15:05 UTC, KwakYV commented on src/main/java/ru/wpz/service/MessageService.java
>          messageDto = messageMapper.mapMessageDto(messageRepository.getMessageBy(message));
А зачем ты повторно вытаскиваешь из базы message, если при save ты уже его получил и можешь использовать его? 
getMessageBy - некорректное наименование метода и из-за этого не подымается бэк, я предлагаю данный метод вообще убрать.

2022-07-21 11:44 UTC, KwakYV reviewed
Нужно отработать по комментариям

2022-07-21 11:44 UTC, KwakYV commented on src/main/java/ru/wpz/service/ReportService.java
> +                .map(device -> {device.getMessages().subList(0,device.getMessages().size() - 1).clear(); return device;})
Не очень понятна логика.  Для чего в анонимной функции вытаскивается список сообщений по устройству? В конце все равно возвращается сам device&

2022-07-21 11:44 UTC, KwakYV commented on src/main/java/ru/wpz/nio_server/WebSocketChannelInitializer.java
> +        pipeline.addLast("httpObjectAggregator", new HttpObjectAggregator(8192));
Это порт websocket сервера?

2022-07-21 11:44 UTC, KwakYV commented on src/main/java/ru/wpz/nio_server/WebSocketServer.java
> +            ChannelFuture channelFuture = serverBootstrap.bind(8189).sync();
Порты лучше передавать из вне через конфигурационный файл

2022-07-21 11:44 UTC, KwakYV commented on src/main/java/ru/wpz/repository/ReportRepository.java
> +public interface ReportRepository extends JpaRepository<Report, UUID> {
А мы же вроде обсуждали, что будем делать не через репозиторий, так как логика скриптов сложная, а через JDBC API и использовать Dao

2022-07-21 11:44 UTC, KwakYV commented on src/main/java/ru/wpz/service/ReportService.java
> +public class ReportService {
Надо пересмотреть реализацию ReportService. В нем должна быть логика, которая оперирует только  результирующими сущностями отчетности, вся логика формирования  сущностей должна быть реализована средствами Ansi SQL

2022-07-21 13:11 UTC, EvgenyKhavdey commented on src/main/java/ru/wpz/service/ReportService.java
> +                .map(device -> {device.getMessages().subList(0,device.getMessages().size() - 1).clear(); return device;})
До этого кода были из базы вытащил все devicem а вместе с ними вытаскиваются все message. На постгре не получмлось написать скрипт чтобы вытащить только последний  message. В этой строчке в коллекции message удаляет все message кроме последнего

2022-07-21 13:14 UTC, EvgenyKhavdey commented on src/main/java/ru/wpz/nio_server/WebSocketChannelInitializer.java
> +        pipeline.addLast("httpObjectAggregator", new HttpObjectAggregator(8192));
максимальная длина агрегированного контента в байтах

2022-07-21 13:14 UTC, EvgenyKhavdey commented on src/main/java/ru/wpz/nio_server/WebSocketServer.java
> +            ChannelFuture channelFuture = serverBootstrap.bind(8189).sync();
ок

2022-07-21 13:16 UTC, EvgenyKhavdey commented on src/main/java/ru/wpz/repository/ReportRepository.java
> +public interface ReportRepository extends JpaRepository<Report, UUID> {
аннотация @Query это аналог JDBC API, получилосб сконфигурировать нужный запрос через нее, по этому я не стал писать лишний код

2022-07-21 13:19 UTC, EvgenyKhavdey commented on src/main/java/ru/wpz/repository/ReportRepository.java
> +public interface ReportRepository extends JpaRepository<Report, UUID> {
единствееное я не сделал ReportDto, Это переделаю

2022-07-21 13:19 UTC, EvgenyKhavdey commented on src/main/java/ru/wpz/service/ReportService.java
> +public class ReportService {
Вот это я не понял

2022-07-22 13:09 UTC, merged